= https://isaqb.org[iSAQB] PDF Theme

This repository contains the *PDF theme* for iSAQB curricula and other official documents.

It contains <<copyrighted,copyrighted work>>.

== Applicability: What this repository is used for
The pdf theme (aka: _style_) can (and should) be used when converting documents written in AsciiDoc to pdf.


== How to use the style

1. Add this repository as a submodule to your git repository containing *OR*

2. Clone or download the repository and copy the contents of the `/style` directory into the root of your repository

If you only use a single title for your document, it will be displayed on the cover page.
You can also define a subtitle, which will be displayed on the cover page as well, but with a different font style:

`= <This Is The Title>: <This Is The Subtitle>`

In the code of your document, you can define the following variable if you need a header text:

`:curriculum-header-title:` This text will be displayed in the header of the PDF.


== How to change the style

Please see the excellent https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[asciidoctor-pdf theming guide] for details.


== How to contribute or participate
You found a bug, have remarks, comments or proposals?

Open an issue or PR.

== Contributors
Work on this pdf theme started in February 2019. The original Asciidoctor pdf theme served as a foundation and was initially slightly modified and enhanced by Dr. Gernot Starke.


[[copyrighted]]
== Licensing and Copyright

[IMPORTANT]
====
THE iSAQB GRAPHICS ARE COPYRIGHTED.

© (Copyright), https://isaqb.org[International Software Architecture Qualification Board e. V.]
(iSAQB® e. V.) 2009-2019
====

The style (without the iSAQB logo) may be used freely.

All parts of this theme (style, dimensions, theme, definitions and all other) come *without any guarantee* - please use on your own risk.  
 
